# Generated by Django 4.1.4 on 2023-01-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
